version: '3.3'

services:

  elasticsearch:
    image: mapleobserver/elastic-elasticsearch:6.2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  logstash:
    image: mapleobserver/elastic-logstash:6.2.4
    ports:
      - "5000:5000"
      - "9600:9600"
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    image: mapleobserver/elastic-kibana:6.2.4
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  filebeat:
    image: mapleobserver/filebeat:6.2.4
    configs:
      - source: filebeat_config
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - /var/lib/docker:/var/lib/docker/
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
    logging:
      driver: journald
    networks:
      - elk
    deploy: 
      mode: global

configs:

  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
  logstash_config:
    file: ./logstash/config/logstash.yml
  logstash_pipeline:
    file: ./logstash/pipeline/logstash.conf
  kibana_config:
    file: ./kibana/config/kibana.yml
  filebeat_config:
    file: ./filebeat/config/filebeat.yml

networks:
  elk:
    driver: overlay
