# 将指定的日志上传的output中去【所有的日志，包括之前的】
# 有一个缺点时，如果重启一次filebeat，则会将之前的内容重复上传
filebeat.prospectors:
- type: docker
  containers.ids:
    - ${data.docker.container.id}
  json.message_key: docker
  json.keys_under_root: true
  processors:
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

# output.logstash:
#   hosts: ["logstash:5000"]