#========================== Filebeat autodiscover ==============================
# 实时监控文件中的内容[但是之前的内容不会上传到output中去]
# 缺点是，如果filebeat没有运行的话，中间产生的日志会缺失
filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            and:
              - regexp: 
                  docker.container.name: '.*'
          config:autodiscover
            - type: docker
              containers.ids:
                - ${data.docker.container.id}
              # paths:
              #   - /var/lib/docker/containers/${data.docker.container.id}/*.log


#=========================== Filebeat prospectors =============================
# filebeat.prospectors:
#   - type: log
#     enabled: true
#     paths:
#       - /var/lib/docker/containers/${data.docker.container.id}/*.log


output.elasticsearch:
  hosts: ['elasticsearch:9200']